#ifndef EMPTYEXAMPLEWITHUI_GLOBAL_H
#define EMPTYEXAMPLEWITHUI_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(EMPTYEXAMPLEWITHUI_LIBRARY)
#  define EMPTYEXAMPLEWITHUISHARED_EXPORT Q_DECL_EXPORT
#else
#  define EMPTYEXAMPLEWITHUISHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // EMPTYEXAMPLEWITHUI_GLOBAL_H
